app:
  filters:
    allowed-fields:
      - status
      - subscription
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
logging:
  level:
    org.springframework.boot.context.properties: DEBUG
    org.springframework.boot.context.config: DEBUG
    org.springframework.boot.context.logging: DEBUG
